name: recsys
channels:
    - conda-forge
dependencies:
    #base packages
    - python=3.7
    - anaconda
    - numpy
    - matplotlib
    - jupyter
    - jupyterlab
    - pillow
    #spatial, statistics and data handling
    - geopandas
    - cartopy
    - verde
     #things that need pip
    - pip
    - pip:
      - sklearn
      - glob2
      - lasio
