name: recsys
channels:
    - conda-forge
dependencies:
    #base packages
    - python=3.8
    - anaconda
    #spatial, statistics and data handling
    - geopandas
    - cartopy
    - verde
     #things that need pip
    - pip
    - pip:
      - sklearn
      - glob2
      - lasio
